# Generated by Django 5.0.6 on 2024-05-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='little_description',
            field=models.CharField(default='', max_length=21),
        ),
    ]
